# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\python\pyqt\demos\ericdemo\news\news0.ui'
#
# Created: Fri May 16 16:55:19 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(885, 616)
        MainWindow.setMinimumSize(QtCore.QSize(80, 0))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 90, 461, 351))
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.testText = QtGui.QPlainTextEdit(self.tab1)
        self.testText.setGeometry(QtCore.QRect(9, 9, 261, 61))
        self.testText.setObjectName(_fromUtf8("testText"))
        self.backbutton = QtGui.QPushButton(self.tab1)
        self.backbutton.setGeometry(QtCore.QRect(150, 90, 75, 23))
        self.backbutton.setObjectName(_fromUtf8("backbutton"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.tableView = QtGui.QTableView(self.tab2)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 601, 331))
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableView.setDragEnabled(True)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.listView = QtGui.QListView(self.tab3)
        self.listView.setGeometry(QtCore.QRect(0, 0, 401, 331))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.tabWidget.addTab(self.tab3, _fromUtf8(""))
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName(_fromUtf8("tab4"))
        self.tabWidget.addTab(self.tab4, _fromUtf8(""))
        self.tab5 = QtGui.QWidget()
        self.tab5.setObjectName(_fromUtf8("tab5"))
        self.tabWidget.addTab(self.tab5, _fromUtf8(""))
        self.tab6 = QtGui.QWidget()
        self.tab6.setObjectName(_fromUtf8("tab6"))
        self.tableWidget = QtGui.QTableWidget(self.tab6)
        self.tableWidget.setGeometry(QtCore.QRect(5, 11, 501, 191))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab6, _fromUtf8(""))
        self.urlLine = QtGui.QLineEdit(self.centralWidget)
        self.urlLine.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.urlLine.setObjectName(_fromUtf8("urlLine"))
        self.categorizebox_p = QtGui.QComboBox(self.centralWidget)
        self.categorizebox_p.setGeometry(QtCore.QRect(270, 30, 69, 22))
        self.categorizebox_p.setObjectName(_fromUtf8("categorizebox_p"))
        self.categorizebox_p.addItem(_fromUtf8(""))
        self.categorizebox_p.addItem(_fromUtf8(""))
        self.categorizebox_p.addItem(_fromUtf8(""))
        self.categorizebox_p.addItem(_fromUtf8(""))
        self.okbutton = QtGui.QPushButton(self.centralWidget)
        self.okbutton.setGeometry(QtCore.QRect(370, 30, 75, 23))
        self.okbutton.setObjectName(_fromUtf8("okbutton"))
        self.bodyedit = QtGui.QTextEdit(self.centralWidget)
        self.bodyedit.setGeometry(QtCore.QRect(510, 129, 360, 321))
        self.bodyedit.setObjectName(_fromUtf8("bodyedit"))
        self.pushButton = QtGui.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 490, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.titleedit = QtGui.QTextEdit(self.centralWidget)
        self.titleedit.setGeometry(QtCore.QRect(510, 10, 360, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleedit.sizePolicy().hasHeightForWidth())
        self.titleedit.setSizePolicy(sizePolicy)
        self.titleedit.setSizeIncrement(QtCore.QSize(2, 0))
        self.titleedit.setObjectName(_fromUtf8("titleedit"))
        self.digestedit = QtGui.QTextEdit(self.centralWidget)
        self.digestedit.setGeometry(QtCore.QRect(510, 49, 360, 61))
        self.digestedit.setObjectName(_fromUtf8("digestedit"))
        self.pushButton_2 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 460, 80, 40))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 460, 80, 40))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(490, 0, 20, 561))
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.categorizebox_m = QtGui.QComboBox(self.centralWidget)
        self.categorizebox_m.setGeometry(QtCore.QRect(580, 470, 69, 22))
        self.categorizebox_m.setObjectName(_fromUtf8("categorizebox_m"))
        self.categorizebox_m.addItem(_fromUtf8(""))
        self.categorizebox_m.addItem(_fromUtf8(""))
        self.categorizebox_m.addItem(_fromUtf8(""))
        self.categorizebox_m.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 885, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu01 = QtGui.QMenu(self.menuBar)
        self.menu01.setObjectName(_fromUtf8("menu01"))
        self.menu02 = QtGui.QMenu(self.menuBar)
        self.menu02.setObjectName(_fromUtf8("menu02"))
        self.menu03 = QtGui.QMenu(self.menuBar)
        self.menu03.setObjectName(_fromUtf8("menu03"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.newAction = QtGui.QAction(MainWindow)
        self.newAction.setObjectName(_fromUtf8("newAction"))
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.newAction)
        self.menu03.addAction(self.newAction)
        self.menuAbout.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu01.menuAction())
        self.menuBar.addAction(self.menu02.menuAction())
        self.menuBar.addAction(self.menu03.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.tableView, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), MainWindow.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.testText.setPlainText(_translate("MainWindow", "test", None))
        self.backbutton.setText(_translate("MainWindow", "backupdate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "tab1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "tab2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "tab3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "tab4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("MainWindow", "tab5", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "22", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "33", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "44", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "cc", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "aa", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "dd", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "tt", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab6), _translate("MainWindow", "页", None))
        self.urlLine.setText(_translate("MainWindow", "test", None))
        self.categorizebox_p.setItemText(0, _translate("MainWindow", "国际", None))
        self.categorizebox_p.setItemText(1, _translate("MainWindow", "体育", None))
        self.categorizebox_p.setItemText(2, _translate("MainWindow", "科技", None))
        self.categorizebox_p.setItemText(3, _translate("MainWindow", "测试", None))
        self.okbutton.setText(_translate("MainWindow", "OK", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_2.setText(_translate("MainWindow", "update", None))
        self.pushButton_3.setText(_translate("MainWindow", "reset", None))
        self.categorizebox_m.setItemText(0, _translate("MainWindow", "国际", None))
        self.categorizebox_m.setItemText(1, _translate("MainWindow", "体育", None))
        self.categorizebox_m.setItemText(2, _translate("MainWindow", "科技", None))
        self.categorizebox_m.setItemText(3, _translate("MainWindow", "测试", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.menu01.setTitle(_translate("MainWindow", "01", None))
        self.menu02.setTitle(_translate("MainWindow", "02", None))
        self.menu03.setTitle(_translate("MainWindow", "03", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.newAction.setText(_translate("MainWindow", "&New", None))
        self.newAction.setShortcut(_translate("MainWindow", "Ctrl+N", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

